from rest_framework import serializers

from .models import Car


class CarSerializer(serializers.Serializer):
    brand_choices = (
        ('', 'همه برند ها'),
        ('audi', 'آئودی'),
        ('arisun', 'آریسان'),
        ('alfa-romeo', 'آلفارومئو'),
        ('opel', 'اُپل'),
        ('swm', 'اس‌دبلیو‌ام'),
        ('smart', 'اسمارت'),
        ('oldsmobile', 'الدزمبیل'),
        ('mg', 'ام‌جی'),
        ('mvm', 'ام‌وی‌ام'),
        ('isuzu', 'ایسوزو'),
        ('iveco', 'ایوکو'),
        ('baic', 'بایک'),
        ('brilliance', 'برلیناس'),
        ('besturn', 'بسترن'),
        ('mercedes-benz', 'بنز'),
        ('borgward', 'بورگوارد'),
        ('bmw', 'بی ام و'),
        ('bisu', 'بیسو'),
        ('byd', 'بی وای دی'),
        ('buick', 'بیوک'),
        ('pazhan', 'پاژن'),
        ('pride', 'پراید'),
        ('peugeot', 'پژو'),
        ('porsche', 'پورشه'),
        ('pontiac', 'پونتیاک'),
        ('paykan', 'پیکان'),
        ('tara', 'تارا'),
        ('toyota', 'تویوتا'),
        ('tiba', 'تیبا'),
        ('jac', 'جک'),
        ('jaguar', 'جگوار'),
        ('joylong', 'جوی‌لانگ'),
        ('jmc', 'جی ام سی'),
        ('jeep', 'جیپ'),
        ('geely', 'جیلی'),
        ('changan', 'چانگان'),
        ('chery', 'چری'),
        ('datsun', 'داتسون'),
        ('domy', 'دامای'),
        ('dongfeng', 'دانگ فنگ'),
        ('daihatsu', 'دایهاتسو'),
        ('delica', 'دلیکا'),
        ('dena', 'دنا'),
        ('dodge', 'دوج'),
        ('daewoo', 'دوو'),
        ('ds', 'دی اس'),
        ('dignity', 'دیگنتی'),
        ('deer', 'دییر'),
        ('runna', 'رانا'),
        ('rayen', 'راین'),
        ('renault', 'رنو'),
        ('rollsroyce', 'رولزرویس'),
        ('rich', 'ریچ'),
        ('rigan', 'ریگان'),
        ('zamyad', 'زامیاد'),
        ('zotye', 'زوتی'),
        ('ssangyong', 'سانگ یانگ'),
        ('saina', 'ساینا'),
        ('seat', 'سئات'),
        ('samand', 'سمند'),
        ('datsun/car', 'سواری داتسون'),
        ('soueast', 'سوئیست'),
        ('subaru', 'سوبارو'),
        ('suzuki', 'سوزوکی'),
        ('citroen', 'سیتروئن'),
        ('sinad', 'سیناد'),
        ('shahin', 'شاهین'),
        ('chevrolet', 'شورولت'),
        ('farda', 'فردا'),
        ('foton', 'فوتون'),
        ('volkswagen', 'فولکس'),
        ('fiat', 'فیات'),
        ('fidelity', 'فیدلیتی'),
        ('capra', 'کاپرا'),
        ('chrysler', 'کرایسلر'),
        ('quick', 'کوئیک'),
        ('kia', 'کیا'),
        ('kmc', 'کی ام سی'),
        ('great-wall', 'گریت وال'),
        ('lada', 'لادا'),
        ('lamborghini', 'لامبورگینی'),
        ('lexus', 'لکسوس'),
        ('land-rover', 'لندرور'),
        ('landmark', 'لندمارک'),
        ('lotus', 'لوتوس'),
        ('luxgen', 'لوکسژن'),
        ('lifan', 'لیفان'),
        ('maserati', 'مازراتی'),
        ('mazda', 'مزدا'),
        ('maxus', 'مکسوس'),
        ('mitsubishi', 'میتسوبیشی'),
        ('mini', 'مینی'),
        ('nissan', 'نیسان'),
        ('arisun/arisun', 'وانت آریسان'),
        ('amico/araz', 'لنکنوانت آمیکو آراز'),
        ('lincoln', 'لنکن'),
        ('pride/pickup', 'وانت پراید'),
        ('gac-gonow/pickup', 'وانت جی‌ای‌سی گونو'),
        ('jeep/pickup', 'وانت جیپ'),
        ('datsun/pickup', 'وانت داتسون'),
        ('deer/deer', 'وانت دییر'),
        ('renault/pickup', 'وانت رنو'),
        ('subaru/pickup', 'وانت سوبارو'),
        ('chevrolet/pickup', 'وانت شورولت'),
        ('foton/pickup', 'وانت فوتون'),
        ('volkswagen/pickup', 'وانت فولکس'),
        ('great-wall/pickup-wingle-3', 'وانت گریت وال'),
        ('toyota/pickup', 'وانت لندکروزر'),
        ('mazda/pickup', 'وانت مزدا'),
        ('mitsubishi/pickup', 'وانت میتسوبیشی'),
        ('hyosow/t205-pickup', 'وانت هیوسو '),
        ('nissan/pickup', 'وانت نیسان'),
        ('maxus', 'مکسوس'),
        ('volvo', 'ولوو'),
        ('irankhodro-van', 'ون ایران خودرو'),
        ('iveco/van', 'ون ایویکو'),
        ('brilliance/van', 'ون برلیانس'),
        ('mercedes-benz/van', 'ون بنز'),
        ('toyota/van', 'ون تویوتا'),
        ('joylong/van', 'ون جوی لانگ'),
        ('delica/van', 'ون دلیکا'),
        ('dodge/van', 'ون دوج'),
        ('renault/van', 'ون رنو'),
        ('saipa', 'ون سایپا'),
        ('chevrolet/van', 'ون شورولت'),
        ('car/faw', 'ون فاو'),
        ('foton/van', 'ون فوتون'),
        ('volkswagen/van', 'ون فولکس'),
        ('kia/van', 'ون کیا'),
        ('great-wall/van', 'ون گریت وال'),
        ('maxus/van', 'ون مکسوس'),
        ('mitsubishi/van', 'ون میتسوبیشی'),
        ('narvan', 'ون نارون'),
        ('hyundai/van', 'ون هیوندای'),
        ('hafei-lobo', 'هافی لوبو'),
        ('hummer', 'هامر'),
        ('haval', 'هاوال'),
        ('haima', 'هایما'),
        ('hanteng', 'هن تنگ'),
        ('honda', 'هوندا'),
        ('hillman', 'هیلمن'),
        ('hyosow', 'هیوسو'),
        ('volkswagen/van', 'ون فولکس'),
        ('hyundai', 'هیوندای'),
        ('uaz', 'یوآز'),
        ('other', 'سایر'),
    )
    brand = serializers.ChoiceField(label='برند', choices=brand_choices)
    name = serializers.CharField(label='مدل', max_length=32)
    kilometer = serializers.CharField(label='کارکرد', max_length=8)
    model = serializers.CharField(label='سال تولید', max_length=4)
    accuracy = serializers.ChoiceField(label='دقت', choices=[('5', 'کم'), ('20', 'متوسط'), ('50', 'زیاد')])


